import Foundation

let runner = TestRunner()
runManifestValidatorTests(runner)
runCharacterPackageLoaderTests(runner)
runTaskStoreTests(runner)
runReminderStoreTests(runner)
runFocusTimerTests(runner)
runFocusHistoryStoreTests(runner)
runWellnessStoreTests(runner)
runScreenTimeStoreTests(runner)
runNudgeAndMessageTests(runner)
runReminderEngineTests(runner)
runProductivityTests(runner)
runAppAwarenessTests(runner)
runAppSettingsTests(runner)
runOnboardingProgressTests(runner)
runProgressionStoreTests(runner)
runPetBrainTests(runner)
runPetStateStoreTests(runner)
runCharacterSystemTests(runner)
runPetPlacementTests(runner)
runActivityTrackerTests(runner)
runActivityTests(runner)
runMoodAndPersonalityTests(runner)
runCharacterActivitySupportTests(runner)
runTrickAndInterruptionTests(runner)
runCompanionExperienceTests(runner)
runPreStage9AuditTests(runner)
runPetModeTests(runner)
runReliabilityTests(runner)
runCharacterIdentityTests(runner)
runCommandFuzzTests(runner)
runEnvironmentObjectTests(runner)
runEnvironmentLongSimulationTests(runner)
runInteractionMemoryTests(runner)
runPetMessagesTests(runner)
runMasterMatrixTests(runner)
runTwentyFourHourSimulationTests(runner)
runRelationshipDepthTests(runner)
runDataPortabilityTests(runner)
runRestartPersistenceTests(runner)

let allPassed = runner.summarize()
exit(allPassed ? 0 : 1)
